enum MessageType {
    MEMBER_JOIN,
    MEMBER_LEFT,
    ITEM_FOCUSED,
    VOTING_STATUS,
    VOTING_RESULT,
    MEMBER_VOTED,
    ITEM_ESTIMATED,
    PLANNING_COMPLETED,
    ANSWER_CREATED,
    ANSWER_DELETED,
    STATUS_CHANGED,
    RETRO_FINISHED
};

export default MessageType;
